### ISSUE TITLE
Plugins for Experimental UI in 2019.1

### ISSUE THREAD

**Issue by vyadh** [JetBrains/teamcity-sdk-docs#8]
I realise the new UI in 2019.1 is experimental, but it would be great to get some information on how to integrate with it.

Specifically, how would a plugin that creates a project tab gain compatibility? Currently such tabs are marked as classic and you have to go back to the normal UI to display them.

Or maybe you're not ready for that yet? Pointers to an unstable API would be fine, I'm interested to know how it's going to work given the more SPA-like TeamCity. Plugins as micro frontends?

**Comment by Blacknikomo** [comment]
Hello @vyadh,

Definitely, that's a nice proposal, thank you!

We are going to introduce the public API and explanation of how to integrate custom tabs into the Experimental UI altogether with the next minor release (2019.2).

There is also a [task](https://youtrack.jetbrains.com/issue/TW-60952), which you could follow to stay tuned with current work on your request.

**Comment by vyadh** [comment]
Sounds great. Thanks!
